stages:
  - build

build_job:
  stage: build
  image: nixos/nix:latest
  variables:
    NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/c898ce22834cf40ea69adf6093755532df412102.tar.gz"
  script:
    - nix-shell --run ls
    - nix-shell --run 'ruby -v'
    - nix-shell --run 'rspec -f doc'
    - nix-build
